#!/usr/bin/env python

import sys, argparse, logging
from cli.argparser import PARSER
from cli.pathing import find, update, nname
from pipeline_manager.initialize import initialize_experiment_db


if __name__ == '__main__':
    args = PARSER.parse_args()
    # verbose = args.v
    
    # if verbose:
    #     print(args)
    
    match args.subcommand:
        case 'find':
            find(**vars(args))
        case 'list':
            pass
        case 'update':
            update(**vars(args))
        case 'nname':
            # special subcase of update that will probably be used a lot
            nname(**vars(args))
        case 'add':
            pass
        case 'init':
            # TODO: wrap this please
            initialize_experiment_db()



