#!/usr/bin/env python
#

# import modules used here -- sys is a very standard one
import sys, argparse, logging
from cli.argparser import PARSER
from cli.pathing import find, update, nname

if __name__ == '__main__':
    args = PARSER.parse_args()
    # verbose = args.v
    
    # if verbose:
    #     print(args)
    
    match args.subcommand:
        case 'find':
            find(**vars(args))
        case 'update':
            update(**vars(args))
        case 'nname':
            # special subcase of update that will probably be used a lot
            nname(**vars(args))
        case 'add':
            pass




